DROP TABLE PRODUTO;

CREATE TABLE PRODUTO(
    COD_PRO NUMBER PRIMARY KEY,
    VALOR NUMBER(10,2),
    COD_CAT CHAR(1)
);

CREATE TABLE ALIQUOTA (
    COD_CAT CHAR(1) PRIMARY KEY,
    IPI NUMBER(5,2)
);

INSERT INTO PRODUTO VALUES (1001, 120.00, 'A');
INSERT INTO PRODUTO VALUES (1002, 250.00, 'B');

INSERT INTO ALIQUOTA VALUES ('A', 10);
INSERT INTO ALIQUOTA VALUES ('B', 15);

COMMIT;

CREATE OR REPLACE PROCEDURE CALCULAR_IPI (
    P_COD_PRO IN NUMBER
)
IS
    V_VALOR   PRODUTO.VALOR%TYPE;
    V_CAT     PRODUTO.COD_CAT%TYPE;
    V_IPI     ALIQUOTA.IPI%TYPE;
    V_RESULT  NUMBER;
BEGIN
    
    SELECT VALOR, COD_CAT
    INTO V_VALOR, V_CAT
    FROM PRODUTO
    WHERE COD_PRO = P_COD_PRO;

  
    SELECT IPI
    INTO V_IPI
    FROM ALIQUOTA
    WHERE COD_CAT = V_CAT;

   
    V_RESULT := V_VALOR * (V_IPI / 100);

    DBMS_OUTPUT.PUT_LINE('Valor do produto: ' || V_VALOR);
    DBMS_OUTPUT.PUT_LINE('Categoria: ' || V_CAT);
    DBMS_OUTPUT.PUT_LINE('IPI (%): ' || V_IPI);
    DBMS_OUTPUT.PUT_LINE('Valor do IPI: R$ ' || V_RESULT);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Produto ou categoria não encontrado.');
END;
/

SET SERVEROUTPUT ON;

BEGIN
    CALCULAR_IPI(1001);
END;
/


