CREATE TABLE ALUNO2(
RA NUMBER,
NOME VARCHAR2(100),
A1 NUMBER,
A2 NUMBER,
A3 NUMBER,
A4 NUMBER,
MEDIA NUMBER(4,2),
RESULTADO VARCHAR2(20)
);

CREATE OR REPLACE PROCEDURE INSERIR_ALUNO2(
    P_RA IN NUMBER,
    P_NOME IN VARCHAR2,
    P_A1   IN NUMBER,
    P_A2   IN NUMBER,
    P_A3   IN NUMBER,
    P_A4   IN NUMBER
)
IS 
    V_MAIOR NUMBER;
    V_MEDIA NUMBER;
    V_RESULT VARCHAR2(20);
BEGIN
    IF 
        P_A1 > P_A2 THEN
            V_MAIOR := P_A1;
        ELSE
            V_MAIOR := P_A2;
        END IF;    
    V_MEDIA := (V_MAIOR + P_A3 + P_A4)/3;
    
    IF V_MEDIA >= 6 THEN
        V_RESULT := 'APROVADO';
    ELSE 
        V_RESULT := 'REPROVADO';
    END IF;
    
    INSERT INTO ALUNO2 (RA, NOME, A1, A2, A3, A4, MEDIA, RESULTADO)
    VALUES (P_RA, P_NOME, P_A1, P_A2, P_A3, P_A4, V_MEDIA, V_RESULT);
    
    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Aluno inserido com sucesso!');
END;
/
SET SERVEROUTPUT ON;

BEGIN
     INSERIR_ALUNO2(123, 'ANTONIO ALVES', 6.5, 3.5, 9.5, 5.0);
END;
/
    SELECT * FROM ALUNO2;    