

CREATE TABLE CLIENTE(
    COD_CLI NUMBER PRIMARY KEY,
    NOME_CLI VARCHAR2(100),
    EMAIL_CLI VARCHAR2(100)
    
);

INSERT INTO CLIENTE (COD_CLI, NOME_CLI, EMAIL_CLI)
VALUES (10, 'BEATRIZ BERNARDES', 'bb@dominio.com.br');
COMMIT;


CREATE OR REPLACE PROCEDURE BUSCAR_CLIENTE (P_COD_CLI IN NUMBER)
IS 
    V_NOME  CLIENTE.NOME_CLI%TYPE;
    v_EMAIL CLIENTE.EMAIL_CLI%TYPE;

BEGIN
    SELECT NOME_CLI, EMAIL_CLI
    INTO V_NOME, V_EMAIL
    FROM CLIENTE
    WHERE COD_CLI = P_COD_CLI;
    
    DBMS_OUTPUT.PUT_LINE('Nome: ' || V_NOME);
    DBMS_OUTPUT.PUT_LINE('Email: ' || V_EMAIL);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Cliente não encontrado.');

END;
/

SET SERVEROUTPUT ON;
BEGIN
BUSCAR_CLIENTE(10);
END;
/