SET SERVEROUTPUT ON;

CREATE TABLE PRODUTO (
    CODIGO NUMBER PRIMARY KEY,
    CATEGORIA CHAR(1),
    VALOR NUMBER(10,2)
);

INSERT INTO PRODUTO (CODIGO, CATEGORIA, VALOR) VALUES (1001, 'A', 7.55);
INSERT INTO PRODUTO (CODIGO, CATEGORIA, VALOR) VALUES (1002, 'B', 5.95);
INSERT INTO PRODUTO (CODIGO, CATEGORIA, VALOR) VALUES (1003, 'C', 3.45);

COMMIT;

SELECT * FROM PRODUTO;





BEGIN 
    UPDATE PRODUTO
     SET VALOR =
      CASE 
        WHEN CATEGORIA = 'A' THEN VALOR * 1.05
        WHEN CATEGORIA = 'B' THEN VALOR * 1.10
        WHEN CATEGORIA = 'C' THEN VALOR * 1.15
        END;
    COMMIT;
END;