CREATE OR REPLACE FUNCTION FAH_PARA_CELSIUS (
    P_F IN NUMBER
) RETURN NUMBER
IS
    V_C NUMBER(10,2);
BEGIN
    V_C := (P_F - 32) / 1.8;
    RETURN V_C;
END;
/

SET SERVEROUTPUT ON;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Celsius: ' || FAH_PARA_CELSIUS(68));
END;
/