CREATE TABLE LUCRO (
    ANO NUMBER PRIMARY KEY,
    VALOR NUMBER(15,2)
);

CREATE TABLE SALARIO (
    MATRICULA NUMBER PRIMARY KEY,
    VALOR NUMBER(10,2)
);

INSERT INTO LUCRO VALUES (2007, 1200000);
INSERT INTO LUCRO VALUES (2008, 1500000);
INSERT INTO LUCRO VALUES (2009, 1400000);

INSERT INTO SALARIO VALUES (1001, 2500);
INSERT INTO SALARIO VALUES (1002, 3200);

COMMIT;

CREATE OR REPLACE PROCEDURE CALCULAR_BONUS (
    P_ANO        IN NUMBER,
    P_MATRICULA  IN NUMBER
)
IS
    V_LUCRO   LUCRO.VALOR%TYPE;
    V_SALARIO SALARIO.VALOR%TYPE;
    V_BONUS   NUMBER(15,2);
BEGIN
   
    SELECT VALOR
    INTO V_LUCRO
    FROM LUCRO
    WHERE ANO = P_ANO;

    
    SELECT VALOR
    INTO V_SALARIO
    FROM SALARIO
    WHERE MATRICULA = P_MATRICULA;

    
    V_BONUS := (V_LUCRO * 0.01) + (V_SALARIO * 0.05);

    DBMS_OUTPUT.PUT_LINE('Lucro: ' || V_LUCRO);
    DBMS_OUTPUT.PUT_LINE('Salário: ' || V_SALARIO);
    DBMS_OUTPUT.PUT_LINE('Bônus: R$ ' || TO_CHAR(V_BONUS, '9999990.00'));

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Ano ou matrícula não encontrado.');
END;
/

SET SERVEROUTPUT ON;

BEGIN
    CALCULAR_BONUS(2007, 1001);
END;
/